import type { MCQThemeConfig, MockTestThemeConfig } from '../types';

export const DEFAULT_MCQ_THEME: MCQThemeConfig = {
  primaryColor: '#4f46e5',
  accentColor: '#10b981',
  backgroundColor: '#f8fafc',
  cardBackgroundColor: '#ffffff',
  textColor: '#0f172a',
  questionBadgeColor: '#4f46e5',
  selectedOptionBorder: '#4f46e5',
  selectedOptionBg: '#eef2ff',
  correctOptionBg: '#ecfdf5',
  correctOptionBorder: '#10b981',
  wrongOptionBg: '#fef2f2',
  wrongOptionBorder: '#ef4444',
  explanationBg: '#f0fdf4',
  actionButtonBg: '#4f46e5',
  actionButtonText: '#ffffff',
  fontFamily: 'Inter, sans-serif',
  borderRadius: '16px',
  presetName: 'Classic Indigo',
};

export const MCQ_THEME_PRESETS: Array<{ name: string; theme: MCQThemeConfig; badgeColor: string }> = [
  {
    name: 'Classic Indigo (Default)',
    badgeColor: '#4f46e5',
    theme: {
      primaryColor: '#4f46e5',
      accentColor: '#10b981',
      backgroundColor: '#f8fafc',
      cardBackgroundColor: '#ffffff',
      textColor: '#0f172a',
      questionBadgeColor: '#4f46e5',
      selectedOptionBorder: '#4f46e5',
      selectedOptionBg: '#eef2ff',
      correctOptionBg: '#ecfdf5',
      correctOptionBorder: '#10b981',
      wrongOptionBg: '#fef2f2',
      wrongOptionBorder: '#ef4444',
      explanationBg: '#f0fdf4',
      actionButtonBg: '#4f46e5',
      actionButtonText: '#ffffff',
      fontFamily: 'Inter, sans-serif',
      borderRadius: '16px',
      presetName: 'Classic Indigo',
    },
  },
  {
    name: 'NTA Official Blue & Emerald',
    badgeColor: '#1e40af',
    theme: {
      primaryColor: '#1e40af',
      accentColor: '#059669',
      backgroundColor: '#f0fdf4',
      cardBackgroundColor: '#ffffff',
      textColor: '#0f172a',
      questionBadgeColor: '#1e40af',
      selectedOptionBorder: '#1e40af',
      selectedOptionBg: '#eff6ff',
      correctOptionBg: '#dcfce7',
      correctOptionBorder: '#16a34a',
      wrongOptionBg: '#fee2e2',
      wrongOptionBorder: '#dc2626',
      explanationBg: '#f0fdf4',
      actionButtonBg: '#1e40af',
      actionButtonText: '#ffffff',
      fontFamily: 'Inter, sans-serif',
      borderRadius: '12px',
      presetName: 'NTA Official Blue',
    },
  },
  {
    name: 'Emerald Scholar Pro',
    badgeColor: '#059669',
    theme: {
      primaryColor: '#059669',
      accentColor: '#d97706',
      backgroundColor: '#f0fdf4',
      cardBackgroundColor: '#ffffff',
      textColor: '#064e3b',
      questionBadgeColor: '#059669',
      selectedOptionBorder: '#059669',
      selectedOptionBg: '#ecfdf5',
      correctOptionBg: '#d1fae5',
      correctOptionBorder: '#059669',
      wrongOptionBg: '#ffe4e6',
      wrongOptionBorder: '#e11d48',
      explanationBg: '#ecfdf5',
      actionButtonBg: '#059669',
      actionButtonText: '#ffffff',
      fontFamily: 'Inter, sans-serif',
      borderRadius: '16px',
      presetName: 'Emerald Scholar',
    },
  },
  {
    name: 'UPSC Amber Gold & Slate',
    badgeColor: '#d97706',
    theme: {
      primaryColor: '#b45309',
      accentColor: '#4338ca',
      backgroundColor: '#fffbeb',
      cardBackgroundColor: '#ffffff',
      textColor: '#451a03',
      questionBadgeColor: '#b45309',
      selectedOptionBorder: '#b45309',
      selectedOptionBg: '#fef3c7',
      correctOptionBg: '#ecfdf5',
      correctOptionBorder: '#10b981',
      wrongOptionBg: '#fef2f2',
      wrongOptionBorder: '#ef4444',
      explanationBg: '#fffbeb',
      actionButtonBg: '#b45309',
      actionButtonText: '#ffffff',
      fontFamily: 'serif',
      borderRadius: '14px',
      presetName: 'UPSC Amber Gold',
    },
  },
  {
    name: 'Cyber Dark Mode Exam',
    badgeColor: '#38bdf8',
    theme: {
      primaryColor: '#38bdf8',
      accentColor: '#34d399',
      backgroundColor: '#0f172a',
      cardBackgroundColor: '#1e293b',
      textColor: '#f8fafc',
      questionBadgeColor: '#0284c7',
      selectedOptionBorder: '#38bdf8',
      selectedOptionBg: '#1e3a8a',
      correctOptionBg: '#064e3b',
      correctOptionBorder: '#10b981',
      wrongOptionBg: '#4c0519',
      wrongOptionBorder: '#f43f5e',
      explanationBg: '#1e293b',
      actionButtonBg: '#0284c7',
      actionButtonText: '#ffffff',
      fontFamily: 'monospace',
      borderRadius: '16px',
      presetName: 'Cyber Dark Mode',
    },
  },
  {
    name: 'Royal Purple & Lavender',
    badgeColor: '#7c3aed',
    theme: {
      primaryColor: '#7c3aed',
      accentColor: '#f43f5e',
      backgroundColor: '#faf5ff',
      cardBackgroundColor: '#ffffff',
      textColor: '#3b0764',
      questionBadgeColor: '#7c3aed',
      selectedOptionBorder: '#7c3aed',
      selectedOptionBg: '#f3e8ff',
      correctOptionBg: '#ecfdf5',
      correctOptionBorder: '#10b981',
      wrongOptionBg: '#fff1f2',
      wrongOptionBorder: '#f43f5e',
      explanationBg: '#faf5ff',
      actionButtonBg: '#7c3aed',
      actionButtonText: '#ffffff',
      fontFamily: 'Inter, sans-serif',
      borderRadius: '20px',
      presetName: 'Royal Purple',
    },
  },
];

export const DEFAULT_MOCK_TEST_THEME: MockTestThemeConfig = {
  primaryColor: '#1e40af',
  headerBgColor: '#0f172a',
  timerColor: '#ef4444',
  questionPaletteStyle: 'nta',
  answeredColor: '#16a34a',
  unansweredColor: '#dc2626',
  markedForReviewColor: '#7c3aed',
  notVisitedColor: '#94a3b8',
  answeredMarkedReviewColor: '#0284c7',
  activeQuestionBorder: '#2563eb',
  submitButtonColor: '#16a34a',
  resultCardBg: '#ffffff',
  darkMode: false,
  presetName: 'NTA Official Standard',
};

export const MOCK_TEST_THEME_PRESETS: Array<{
  name: string;
  theme: MockTestThemeConfig;
  badgeColor: string;
}> = [
  {
    name: 'NTA Official Standard (Green/Red/Violet Palette)',
    badgeColor: '#1e40af',
    theme: {
      primaryColor: '#1e40af',
      headerBgColor: '#0f172a',
      timerColor: '#ef4444',
      questionPaletteStyle: 'nta',
      answeredColor: '#16a34a',
      unansweredColor: '#dc2626',
      markedForReviewColor: '#7c3aed',
      notVisitedColor: '#94a3b8',
      answeredMarkedReviewColor: '#0284c7',
      activeQuestionBorder: '#2563eb',
      submitButtonColor: '#16a34a',
      resultCardBg: '#ffffff',
      darkMode: false,
      presetName: 'NTA Official Standard',
    },
  },
  {
    name: 'Modern Clean Indigo & Teal',
    badgeColor: '#4f46e5',
    theme: {
      primaryColor: '#4f46e5',
      headerBgColor: '#1e1b4b',
      timerColor: '#f59e0b',
      questionPaletteStyle: 'modern',
      answeredColor: '#10b981',
      unansweredColor: '#f43f5e',
      markedForReviewColor: '#8b5cf6',
      notVisitedColor: '#cbd5e1',
      answeredMarkedReviewColor: '#06b6d4',
      activeQuestionBorder: '#4f46e5',
      submitButtonColor: '#4f46e5',
      resultCardBg: '#ffffff',
      darkMode: false,
      presetName: 'Modern Clean Indigo',
    },
  },
  {
    name: 'UPSC Civil Services Classic',
    badgeColor: '#b45309',
    theme: {
      primaryColor: '#b45309',
      headerBgColor: '#292524',
      timerColor: '#ea580c',
      questionPaletteStyle: 'cards',
      answeredColor: '#15803d',
      unansweredColor: '#b91c1c',
      markedForReviewColor: '#6d28d9',
      notVisitedColor: '#a8a29e',
      answeredMarkedReviewColor: '#0369a1',
      activeQuestionBorder: '#b45309',
      submitButtonColor: '#15803d',
      resultCardBg: '#fffbeb',
      darkMode: false,
      presetName: 'UPSC Classic',
    },
  },
  {
    name: 'Dark Mode Cyber Exam (High Contrast)',
    badgeColor: '#38bdf8',
    theme: {
      primaryColor: '#0284c7',
      headerBgColor: '#020617',
      timerColor: '#f43f5e',
      questionPaletteStyle: 'nta',
      answeredColor: '#10b981',
      unansweredColor: '#ef4444',
      markedForReviewColor: '#a855f7',
      notVisitedColor: '#475569',
      answeredMarkedReviewColor: '#38bdf8',
      activeQuestionBorder: '#38bdf8',
      submitButtonColor: '#10b981',
      resultCardBg: '#1e293b',
      darkMode: true,
      presetName: 'Cyber Dark Mode',
    },
  },
];
